version: "3"
services:
  redis:
    image: redis
    domainname: redis.svc
    networks:
      - backend
  api:
    image: python-test:latest
    depends_on:
      - redis
    links:
      - "redis:redis.svc"
    volumes:
      - "./src:/project/api/src"
    environment:
      REDIS_HOST: redis.svc
      REDIS_PORT: 6379
      BIND_PORT: 8080
    ports:
      - 8080:8080
    networks:
      - backend


networks:
  backend:
    driver: bridge

  